### ISSUE TITLE
Exception occured : icloud is not supported

### ISSUE THREAD

**Issue by bomdurup** [unvsDev/corona-alpha#3]
![93EB1AB3-E029-45FD-BE71-E613EF3DA62C](https://user-images.githubusercontent.com/46495515/103444957-ab317680-4cb1-11eb-9bb4-ce379fc4fd43.png)

Scriptable앱에 icloud 사용 체크 되어있는데 다른 부분도 확인해보아야 하는 것이 있을까요?

**Comment by unvsDev** [comment]
데이터 저장을 위해, 설정에서 iCloud Drive를 활성화해주셔야 합니다! Scriptable과 별개의 항목이니 확인 부탁드립니다 :D

**Comment by bomdurup** [comment]
말씀하신대로 Drive가 꺼져있어서군요. 감사합니다!
