### ISSUE TITLE
The label "카카오페이로 기부하기" is out of position.

### ISSUE THREAD

**Issue by unstable-code** [unvsDev/corona-alpha#4]
![IMG_1007](https://user-images.githubusercontent.com/25660580/105591877-cf2a3880-5dd5-11eb-93e9-eec128442dc2.jpg)

위 사진과 같이 **카카오페이로 기부하기**의 제목과 설명이 해당 테이블 셀 영역을 벗어났습니다. 

### 디바이스 정보
- iPhone Xs 14.3
- Scriptable 버전: 1.6.3
- 유동적 텍스트 크기: 기본값

**Comment by unvsDev** [comment]
문제를 확인했습니다. 차기 업데이트에서 해당 이슈가 개선될 예정입니다. 현재는 디바이스의 텍스트 크기를 조절하셔서 해당 문제를 임시적으로 해결하실 수 있습니다.

**Comment by unvsDev** [comment]
v1.4.1 업데이트를 확인해주세요. 해당 이슈를 해결했습니다.
