### ISSUE TITLE
220130_3.3 버전 에러

### ISSUE THREAD

**Issue by root-devvoo** [unvsDev/corona-alpha#7]
갑자기 오늘부터 아래와 같은 에러가 발생합니다. 확인 부탁드립니다 :)

![543B5066-8F13-4A53-937F-360FD160A504](https://user-images.githubusercontent.com/78403443/151701277-57a68bc1-b9f1-4422-84c0-b5088101781e.jpeg)

![EFA4C9EF-F47A-4371-ACD1-044DEDB4B09E](https://user-images.githubusercontent.com/78403443/151701282-bd6aa189-6c85-4972-9e1d-bd00e530948d.jpeg)

**Comment by unvsDev** [comment]
v3.4에서 해당 버그가 수정되었습니다. 감사합니다 :)
